### ISSUE TITLE
tgentools: set number of xz threads to -m arg

### ISSUE THREAD

**Issue by jtracey** [shadow/tgen#12]
When tgentools saves its results, it currently uses a [hard-coded thread count of 3 for xz](https://github.com/shadow/tgen/blob/8825a1500cda63e81499be95a60d2783267c39cd/tools/tgentools/util.py#L228). For large experiments on machines with lots of cores, I've found that this ends up being the processing bottleneck. Using as many threads as specified with the `-m` arg  would be a nice feature to have.

**Comment by robgjansen** [comment]
Fixed in #55
