### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by MrZz233** [shadow/tgen#31]
Dear author. I encountered  link errors when I run make. It happened on ubuntu20.04
![image](https://user-images.githubusercontent.com/25599503/164886664-ad7d3477-1551-4ff8-babd-87fbd09323f8.png)
How can I fix it? Thanks.

**Comment by robgjansen** [comment]
Please make sure you have `libxml2` installed:

```
sudo apt install -y libxml2 libxml2-dev
```

If it is already installed, then this might help?
- https://stackoverflow.com/questions/41847298/xmlstrequal-when-import-igraph-graph-linking-libxml2

**Comment by MrZz233** [comment]
Thank you. I fixed it, but I have a new problem as follow:

![image](https://user-images.githubusercontent.com/25599503/167761815-62503e0d-e3ef-4e1f-8413-f75276078598.png)

When I run the shadow's test, it happend.

**Comment by stevenengler** [comment]
> Thank you. I fixed it, but I have a new problem as follow:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/25599503/167761815-62503e0d-e3ef-4e1f-8413-f75276078598.png)
> 
> 
> 
> When I run the shadow's test or run the tornettools simulation, it happened.  
> 
> It didn't happen in my another computer, so I have no idea to repair this. 

That looks like an interesting error :) Can you make a new issue at https://github.com/shadow/shadow/issues? Please copy the output text into the issue (rather than just a screenshot), and tell us the output of `uname -a`?

**Comment by stevenengler** [comment]
@sporksmith My guess is that the file system that shadow or its dynamically loaded libraries is running on uses 64-bit inodes?

**Comment by MrZz233** [comment]
> RUST_BACKTRACE=1

ok,I'm going to add a new issue in shadow. Thanks
