### ISSUE TITLE
Problems installing tgen on arch

### ISSUE THREAD

**Issue by Lambru99** [shadow/tgen#53]
Hi, i'm trying to install tgen on arch and the process fail during the make command.

> ➜  build git:(main) make
[  5%] Building C object src/CMakeFiles/tgen.dir/tgen-config.c.o
[ 10%] Building C object src/CMakeFiles/tgen.dir/tgen-driver.c.o
[ 15%] Building C object src/CMakeFiles/tgen.dir/tgen-generator.c.o
[ 20%] Building C object src/CMakeFiles/tgen.dir/tgen-graph.c.o
[ 25%] Building C object src/CMakeFiles/tgen.dir/tgen-io.c.o
[ 30%] Building C object src/CMakeFiles/tgen.dir/tgen-log.c.o
[ 35%] Building C object src/CMakeFiles/tgen.dir/tgen-main.c.o
[ 40%] Building C object src/CMakeFiles/tgen.dir/tgen-markovmodel.c.o
[ 45%] Building C object src/CMakeFiles/tgen.dir/tgen-optionparser.c.o
[ 50%] Building C object src/CMakeFiles/tgen.dir/tgen-peer.c.o
[ 55%] Building C object src/CMakeFiles/tgen.dir/tgen-pool.c.o
[ 60%] Building C object src/CMakeFiles/tgen.dir/tgen-server.c.o
[ 65%] Building C object src/CMakeFiles/tgen.dir/tgen-stream.c.o
[ 70%] Building C object src/CMakeFiles/tgen.dir/tgen-timer.c.o
[ 75%] Building C object src/CMakeFiles/tgen.dir/tgen-transport.c.o
[ 80%] Linking C executable tgen
/usr/bin/ld: warning: libcxsparse.so.3, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_qr'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_ltsolve'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_usolve'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_lusol'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_dropzeros'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_fkeep'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_multiply'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_droptol'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_lu'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_dupl'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_compress'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_sfree'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_utsolve'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_spfree'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_ipvec'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_sprealloc'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_add'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_spalloc'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_permute'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_transpose'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_entry'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_gaxpy'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_happly'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_nfree'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_sqr'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_realloc'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_cholsol'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libigraph.so: undefined reference to `cs_di_lsolve'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/tgen.dir/build.make:323: src/tgen] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: src/CMakeFiles/tgen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by jtracey** [comment]
Do you know where on your system the `libcxsparse.so.3` file is?

**Comment by robgjansen** [comment]
I'm assuming this has been resolved, but please reopen if you have further details and still want help resolving it.
